### ISSUE TITLE
Errors communicating with adb are not shown

### ISSUE THREAD

**Issue by kvdb** [lbdremy/grunt-cordova-cli#1]
The emulate command started the emulator, but failed to run anything.

This revealed the issue:

```
$ adb install HelloCorodva-debug.apk
Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE]
```

I suspect these errors are swallowed by grunt-cordova-cli.
It would be very useful to see them.

Thanks for your otherwise very useful grunt task.

**Comment by lbdremy** [comment]
Hi @kvdb,

Ok that's strange, I really don't know what so say considering that I had the exact issue installing an app with this error "INSTAL_FAILED_INSUFFICIENT_STORAGE" but I did have the stackstrace and error message running grunt. Maybe  there is some sort of flag in grunt that you can set to hide error? I did nothing special, no extra flag to run grunt, I use the latest grunt version that's pretty much it. Sorry not really useful advice, what kind of thing happen when running grunt no error, no message nothing, does it just silently failed?

**Comment by kvdb** [comment]
Version from package.json:

```
"grunt": "~0.4.2",
"grunt-bower-task": "~0.3.4",
"grunt-cordovacli": "~0.3.3",
```

I don't have the exact message around anymore, but I'm sure it was green letters telling me "Done, without errors." at the end.
If I see something like this pop up again, I'll make sure to re-open this issue and provide you more details.

**Comment by lbdremy** [comment]
Cool thanks! Let me know
